/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.24
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DealersAndVehicles);
  }
}(this, function(expect, DealersAndVehicles) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DealersAndVehicles.DealersApi();
  });

  describe('(package)', function() {
    describe('DealersApi', function() {
      describe('getDealer', function() {
        it('should call getDealer successfully', function(done) {
          // TODO: uncomment, update parameter values for getDealer call and complete the assertions
          /*
          var datasetId = "datasetId_example";
          var dealerid = 56;

          instance.getDealer(datasetId, dealerid, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DealersAndVehicles.DealersResponse);
            expect(data.dealerId).to.be.a('number');
            expect(data.dealerId).to.be(0);
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
