/*
 * DealersAndVehicles
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.24
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DealersAndVehicles);
  }
}(this, function(expect, DealersAndVehicles) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AnswerResponse', function() {
      beforeEach(function() {
        instance = new DealersAndVehicles.AnswerResponse();
      });

      it('should create an instance of AnswerResponse', function() {
        // TODO: update the code to test AnswerResponse
        expect(instance).to.be.a(DealersAndVehicles.AnswerResponse);
      });

      it('should have the property success (base name: "success")', function() {
        // TODO: update the code to test the property success
        expect(instance).to.have.property('success');
        // expect(instance.success).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property totalMilliseconds (base name: "totalMilliseconds")', function() {
        // TODO: update the code to test the property totalMilliseconds
        expect(instance).to.have.property('totalMilliseconds');
        // expect(instance.totalMilliseconds).to.be(expectedValueLiteral);
      });

    });
  });

}));
